export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_PARKINGSLOTS_SUCCESS = 'LOAD_PARKINGSLOTS_SUCCESS';
export const LOAD_SUB_SLOTS = 'LOAD_SUB_SLOTS';
export const BOOK_PARKINGSLOTS_SUCCESS = 'BOOK_PARKINGSLOTS_SUCCESS';

